SELECT ENAME, SALARY , SALARY+300 AS PLUS300 
FROM EMPLOYEE;

SELECT ENAME, SALARY , SALARY*12+100 AS ¿¬ºÀ 
FROM EMPLOYEE
ORDER BY ¿¬ºÀ DESC;

SELECT ENAME ,SALARY 
FROM EMPLOYEE 
WHERE SALARY >2000
ORDER BY SALARY DESC;

SELECT ENAME,DNO
FROM EMPLOYEE
WHERE ENO = 7788;

SELECT ENAME, SALARY
FROM EMPLOYEE
WHERE SALARY NOT BETWEEN 2000 AND 3000;

SELECT ENAME,JOB,HIREDATE 
FROM EMPLOYEE
WHERE HIREDATE BETWEEN '81/02/20' AND '81/05/01';

SELECT ENAME,DNO
FROM EMPLOYEE
WHERE DNO IN(20,30)
ORDER BY ENAME;

SELECT ENAME,SALARY,DNO
FROM EMPLOYEE
WHERE SALARY BETWEEN 2000 AND 3000 
AND DNO IN(20,30)
ORDER BY ENAME ASC;

SELECT ENAME,HIREDATE
FROM EMPLOYEE
WHERE HIREDATE LIKE '81%';

SELECT ENAME, JOB
FROM EMPLOYEE
WHERE MANAGER IS NULL;

SELECT ENAME,SALARY,COMMISSION
FROM EMPLOYEE
WHERE COMMISSION IS NOT NULL
ORDER BY SALARY, COMMISSION;

SELECT ENAME FROM EMPLOYEE
WHERE ENAME LIKE '__R%';

SELECT ENAME FROM EMPLOYEE
WHERE ENAME LIKE '%A%E%' OR ENAME LIKE '%E%A%';

SELECT ENAME FROM EMPLOYEE
WHERE ENAME LIKE '%A%' AND ENAME LIKE '%E%';

SELECT ENAME,JOB,SALARY FROM EMPLOYEE
WHERE (JOB ='CLERK' OR JOB ='SALESMAN')
AND SALARY NOT IN(1600,950,1300);

SELECT ENAME , JOB, SALARY FROM EMPLOYEE
WHERE JOB IN('CLERK','SALESMAN')
AND SALARY NOT IN(1600,950,1300);

SELECT ENAME ,SALARY,COMMISSION FROM EMPLOYEE
WHERE COMMISSION >=500;

SELECT SALARY FROM EMPLOYEE
ORDER BY SALARY DESC;

SELECT ENAME, SALARY, SALARY + 300
FROM EMPLOYEE;

SELECT ENAME, SALARY, SALARY*12+100 AA
FROM EMPLOYEE
ORDER BY AA DESC;

SELECT ENAME, SALARY
  FROM EMPLOYEE
 WHERE SALARY>2000
 ORDER BY SALARY DESC;
 
SELECT ENAME, DNO
  FROM EMPLOYEE
 WHERE DNO IN (20, 30)
 ORDER BY ENAME DESC;
 
SELECT ENAME, SALARY ,DNO
  FROM EMPLOYEE
 WHERE SALARY BETWEEN 2000 AND 3000
   AND DNO IN (20, 30)
 ORDER BY ENAME;
 
 
SELECT ENAME ,HIREDATE
  FROM EMPLOYEE
 WHERE HIREDATE LIKE '81%';
 
SELECT ENAME , JOB ,SALARY
  FROM EMPLOYEE
 WHERE JOB IN('CLERK','SALESMAN')
   AND SALARY NOT IN(1600,950,1300);
   
SELECT ENAME, SALARY
  FROM EMPLOYEE
 WHERE COMMISSION >=500;
 
 
 
 --1.
SELECT ENO, ENAME, SALARY
  FROM EMPLOYEE
 WHERE DNO = 10;
 
 --2.
SELECT ENAME, HIREDATE, DNO
  FROM EMPLOYEE
 WHERE ENO=7369;

 --3.
SELECT ENAME, HIREDATE, DNO
  FROM EMPLOYEE
 WHERE ENO >7300 AND ENO <7400;
 
 --4.
SELECT * FROM EMPLOYEE
 ORDER BY ENO DESC;
 
 --5.
SELECT ENO, ENAME
  FROM EMPLOYEE
 WHERE ENAME LIKE 'S%';
 
 --6.
SELECT * FROM EMPLOYEE
 WHERE MANAGER IS NULL;
 
 --------------------------------
 
 --1.
SELECT * FROM EMPLOYEE
 WHERE JOB ='SALESMAN' OR JOB ='ANALYST';
 
SELECT * FROM EMPLOYEE
 WHERE JOB LIKE 'SALES%' OR JOB LIKE 'ANAL%';

SELECT * FROM EMPLOYEE
 WHERE JOB IN ('SALESMAN' , 'ANALYST');
 
 --2.
SELECT * FROM EMPLOYEE
 WHERE HIREDATE BETWEEN '81/5/1' AND '82/2/1'
 ORDER BY DNO;
 
 --3.
SELECT ENAME, ENO FROM EMPLOYEE
 WHERE HIREDATE LIKE '81%'
 ORDER BY ENO DESC;
 
 --4.
SELECT ENAME, HIREDATE, SALARY*1.1 AS SALARY2
  FROM EMPLOYEE
 WHERE JOB ='SALESMAN';
 
 --5.
SELECT ENAME,NVL(COMMISSION,0) + 200 AS COMMISSION2
  FROM EMPLOYEE;

 --6.
SELECT ENAME, NVL2(COMMISSION,'Y','N'), COMMISSION
  FROM EMPLOYEE;
  
 --7.
SELECT AVG(SALARY) AS Æò±ÕÀÓ±Ý
  FROM EMPLOYEE
 WHERE HIREDATE LIKE '81%';

 


 --8.
SELECT ENO, ENAME, SALARY +NVL(COMMISSION,0) AS ÃÑ±Þ¿©
  FROM EMPLOYEE;

 


 

